
swagger: "2.0"
info:
  title: PasswordManager
  description: Store your passwords in this database for safe keeping
  version: 0.1.9
servers:
  - url: http://localhost:3001
    description: localhost server
paths:
  /passwords:
    get:
      summary: Returns all accounts with passwords as their hashed values
      responses:
        '200':    # status code
          description: A JSON array of user account objects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
